### ISSUE TITLE
Chipsのコンテンツ領域が足りない

### ISSUE THREAD

**Issue by MeilCli** [NUmeroAndDev/MaterialGallery-android#54]
画面幅が足りないと縦方向にスクロールが必要になります🙏

https://github.com/NUmeroAndDev/MaterialGallery-android/blob/3ca321c79c0b0981e211a12958d2b319e20cc237/app/src/main/res/layout/activity_chip.xml#L23

**Comment by NUmeroAndDev** [comment]
@MeilCli 
Thanks for your report. 🙏 
I fixed it with #58 .
So close this issue.
